apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  # spec for deployment
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
    # spec for pods
    # blueprint for pods
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        # this containerPort should match
        # targetPort in nginx service file.
        - containerPort: 8080

# NOTE:
# Good practice is to store these yaml files
# with Code, sort of IAAC.